# Generated by Django 5.1.5 on 2025-04-06 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.TextField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_ad', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='food.food')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodRecommendation',
        ),
    ]
